### ISSUE TITLE
Unable to take backup DS to google storage workload identity

### ISSUE THREAD

**Issue by paritoshdubey** [ForgeRock/ds-operator#63]
Hi All,

We are not able to take backup of forgerock DS to google storage buckets using workload identity. Our company policy doesnt allow us to create Service account keys for SAs. We are using forgerock DS version 7.1 in GKE environment version 1.20. Please let me know how can we schedule backup of DS without using google SA JSON keys.

**Comment by wstrange** [comment]
I have added a sample in https://github.com/ForgeRock/ds-operator/tree/master/tests/gcs that demonstrates syncing the contents of the backup PVC with a GCS storage bucket. The sample uses workload identity
